spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

camunda:
  bpm:
    admin-user:
      id: test
      first-name: test
      password: test
    filter:
      create: All tasks

kafka:
  enabled: ${KAFKA_ENABLED:true}
  bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:29092}

logging:
  level:
    com.example.KafkaCamundaTest: debug
server:
  port: 8088
